Repository Pbatch/ClashRoyaleBuildABot, pull requests merged in 2024-09, with the labels that each got.

#235 check for updates
  clashroyalebuildabot/utils/git_utils.py
  main.py
Labels: enhancement

#236 add warning and skip git updates if no git repository found
  clashroyalebuildabot/utils/git_utils.py
Labels: bug

#234 GUI
  .pylintrc
  clashroyalebuildabot/bot/bot.py
  clashroyalebuildabot/config.yaml
  clashroyalebuildabot/gui/animations.py
  clashroyalebuildabot/gui/gameplay_widget.py
  clashroyalebuildabot/gui/layout_setup.py
  clashroyalebuildabot/gui/log_handler.py
  clashroyalebuildabot/gui/main_window.py
  clashroyalebuildabot/gui/styles.py
  clashroyalebuildabot/gui/utils.py
  clashroyalebuildabot/utils/logger.py
  clashroyalebuildabot/visualizer.py
  logo.png
  main.py
  pyproject.toml
Labels: enhancement

#238 add "in_game_overtime" screen to screen detector
  clashroyalebuildabot/images/screen/in_game_overtime.jpg
  clashroyalebuildabot/namespaces/screens.py
Labels: bug

#253 add wikified errors in the whole project + pylint (my eyes bleed)
  clashroyalebuildabot/actions/generic/action.py
  clashroyalebuildabot/bot/bot.py
  clashroyalebuildabot/detectors/card_detector.py
  clashroyalebuildabot/detectors/detector.py
  clashroyalebuildabot/emulator/emulator.py
  clashroyalebuildabot/gui/main_window.py
  clashroyalebuildabot/gui/utils.py
  clashroyalebuildabot/utils/error_handling.py
  clashroyalebuildabot/utils/git_utils.py
  error_handling/__init__.py
  error_handling/wikify_error.py
  main.py
Labels: documentation
